### ISSUE TITLE
Minimal Maven pom does not work

### ISSUE THREAD

**Issue by laeubi** [eclipse/lemminx-maven#394] opened 2023-04-26 07:26 UTC
Maven [describes the minmal pom](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html) as:

```
    <project>
      <modelVersion>4.0.0</modelVersion>
     
      <groupId>com.mycompany.app</groupId>
      <artifactId>my-app</artifactId>
      <version>1</version>
    </project>
```

using such xml leads to handling lemminx it as a plain xml file with missing grammar.

**Comment by vrubezhny** [comment] 2023-04-26 11:43
Could you please give more details on lemminx-maven or m2e-core version used?

And what do you mean by "handling ... as plain xml with missing grammar"? Is it about the "No grammar constraints (DTD or XML Schema)." problem appearing?

Did you created a file and copy-pasted the minimal pom's content into it or opened an existing file in editor? 
Do you have any other maven projects in your workspace that probably cannot be normally built (like having broken xml structure, empty files etc.)?

Thanks in advance

**Comment by angelozerr** [comment] 2023-07-28 12:06
Indeed you need to declare the XSD to benefit with XML completion / validation based on XSD. LemMinX maven could embeds the maven XSD and provide a LemMinX URIExtensionResolver to support this usecase.

**Comment by mickaelistria** [comment] 2023-08-17 12:13
This is more or less a duplicate of #201 , let's close.

**Closed by mickaelistria** 2023-08-17 12:13 UTC
Labels: bug
