### ISSUE TITLE
Artifact completions not working

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#123] opened 2020-07-29 17:19 UTC
The remote indexes are present in the index location. But the artifacts groupIds nor artifactIds are not suggested for dependencies.
OS: Windows10

**Comment by mickaelistria** [comment] 2020-07-29 17:21
Please provide steps to reproduce this issue.

**Comment by gayanper** [comment] 2020-07-29 17:39
```
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>arquillian-client</artifactId>
    <dependencies>
        <dependency>
            <groupId>org.wildfly</groupId>
            <artifactId>wildfly-ejb-client-bom</artifactId>
            <version>20.0.0.Final</version>
            <type>pom</type>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>$</groupId>
        </dependency>
    </dependencies>

</project>
```

- Take the following project pom. 
- Open in the generic text editor
- Try  invoke content assist at $ sign.

- On Windows no completions even after the remote indexes are updated.
- On Mac i get local repository completion with the completion item saying remote repos are updating.

**Comment by gayanper** [comment] 2020-07-29 17:53
I even tried a fresh build by cloning the repo and patching the lemmix m2e jar on windows.

**Comment by AObuchow** [comment] 2020-07-29 18:19
@gayanper thank you very much for the steps to reproduce, now a test case can be made for this since we have windows CI

**Comment by gayanper** [comment] 2020-07-29 19:35
@AObuchow i just checked my Windows machine again and it seems it doesn't work when the local repository is not in the default location which is inside users home. Because in my windows machine i had the local repo on drive root and set the path in settings.

i also had the following symlink as well
c:\m2_repo -> c:\Users\{user.name}\.m2\repository

but that didn't work as well.

So i endup moving the repo to c:\Users\{user.name}\.m2\repository to this folder and adding symlink to maven configuration at c:\Users\{user.name}\.m2\settings.xml which made the completions to work without any issue.

**Comment by AObuchow** [comment] 2020-07-29 20:50
@gayanper okay so I think this could be resolved by improving the integration of m2e and lemminx-maven so that m2e can send the location of the local repository?

**Comment by martinlippert** [comment] 2020-08-06 11:19
I am also having issues getting the artifact completion to work. Following the demo on the readme, there is nothing that shows up for me, only the XSD-based elements, but no artifacts. Anything that I need to setup here to make this work? Or anything that I can do to further debug/analyze this?

**Comment by mickaelistria** [comment] 2020-08-06 12:01
@martinlippert Do you also use a different m2 repo than default? Can you successfully run the lemminx-maven test locally?

**Comment by martinlippert** [comment] 2020-08-06 13:59
@mickaelistria cloned the project and ran the built. It indeed fails with a test failure:

```
[ERROR] testDownloadArtifactOnHover(org.eclipse.lemminx.maven.test.RemoteRepositoryTest)  Time elapsed: 15.013 s  <<< ERROR!
org.junit.runners.model.TestTimedOutException: test timed out after 15000 milliseconds
	at org.eclipse.lemminx.maven.test.RemoteRepositoryTest.testDownloadArtifactOnHover(RemoteRepositoryTest.java:107)
```

At the beginning of the test execution output log is something like (in case that is related):

`Central repository index disabled`

Any idea what I can look at to solve this?

**Comment by mickaelistria** [comment] 2020-08-07 09:31
The "Central repository index disabled" is expected and desired during tests.
The "testDowloadArtifactsOnHover" isn't high prirority to you.
I suggest you review the existing completion tests, and if you find the case you wish to see supported is missing, add it. If you cannot reproduce it with unit tests on server side, verify using the language server logs from Eclipse IDE whether the LS does send the expected result (in which case it could be a LSP4E filtering bug).

**Comment by martinlippert** [comment] 2020-08-07 11:04
Not sure why, but things work now (for unknown reasons). Maybe related to the repo index not being around and took a whole while to download in the background (or wasn't triggered). Just guessing here...

Where are those repository indexes stored locally on my machine? Maybe I can try to reproduce the issue again...

**Comment by gayanper** [comment] 2020-08-07 12:08
${user}/.lemminx/ you should find cache and index folder

**Comment by martinlippert** [comment] 2020-08-14 11:36
Thanks @gayanper, tried again and deleted the lemminx cache upfront, but it still works just fine. Since I cannot reproduce this anymore, there is nothing I can add here... :-( So please ignore my complaint about this not working... :-)

**Comment by mickaelistria** [comment] 2020-09-03 15:29
@gayanper Can you please try lattest m2e release (1.16.2 IIRC), it includes latest release of lemminx-maven, which may have it fixed.
Please note that with this release, the index directory is them moved to ~/.m2/repository/index . This is often more appropriate.

**Comment by mickaelistria** [comment] 2020-12-04 22:22
Closing by lack of feedback. Please reopen with more details to reproduce if issue still happens with latest snapshots.

**Closed by mickaelistria** 2020-12-04 22:22 UTC
Labels: bug
