### ISSUE TITLE
[critical] lemminx-maven doesn't take global settings file into account.

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#42] opened 2020-04-30 18:57 UTC
The current implementation depends on the default maven local repository. Also it doesn't support to read the setting files specified in the m2e settings. This cause issue with custom maven configuration where we have defined mirrors.

**Comment by gayanper** [comment] 2020-04-30 19:02
@mickaelistria What should we do, How we can take in the settings we have in m2e for global configuration. If we take the global configuration that will solve many issues I see. One way would be to first try to M2 environment variable and fallback to maven.repo.local system settings and fallback to hardcoded one when resolving the settings file. The best is the take the m2e settings, but I think that will be challenging this is running as a separate process.

**Comment by AObuchow** [comment] 2020-04-30 19:06
> The current implementation depends on the default maven local repository.

 We currently have a [system property](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenPlugin.java#L50) to define the location of the maven local repository. Maybe if an environment variable was used, the user could specify the location of their local maven repository.

 >Also it doesn't support to read the setting files specified in the m2e settings. This cause issue with custom maven configuration where we have defined mirrors.

For mirrors defined in the global `settings.xml` file, we still have to [add support for reading these repositories](https://github.com/eclipse/lemminx-maven/blob/master/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/searcher/RemoteRepositoryIndexSearcher.java#L117)

Since this project is editor agnostic (it's an extension to a language server which can be used by any LS client-editor), we can't call the m2e API to get the settings files.

**Comment by AObuchow** [comment] 2020-04-30 19:07
Yes the M2 environment variable should probably be used

**Comment by mickaelistria** [comment] 2020-04-30 19:30
I started investigating about preferences in https://github.com/eclipse/lemminx-maven/pull/34  and it's kind of working-ish. However, we'd need to do that eagerly and look first at settings, and then override what has to be overridden later.
I think there are actually different issues, which should be treated separately
1. Read settings and honer them (#34 probably already fix it partly)
2. let settings be overridden with system property (maven.repo.local)
3. Allow different settings

**Comment by gayanper** [comment] 2020-04-30 19:46
@mickaelistria can we pass the system properties you care reading at SettingsXmlConfigurationProcessor as VM arguments at https://github.com/eclipse/wildwebdeveloper/blob/0daf7398e1fa7aa8adfda6585d74fec6a9badff2/org.eclipse.wildwebdeveloper.xml/src/org/eclipse/wildwebdeveloper/xml/internal/XMLLanguageServer.java#L41

maybe we can only pass some prefixed system properties from the parent jvm to xmlserver jvm.

**Comment by mickaelistria** [comment] 2020-04-30 19:58
> maybe we can only pass some prefixed system properties from the parent jvm to xmlserver jvm.
M2e can populate those prefixed system properties with the settings. It's not the perfect solution.

We'll see in a later patch, as we first need to have settings working anyway, at least default one before adding some customization here.

**Comment by mickaelistria** [comment] 2020-04-30 21:34
I improved https://github.com/eclipse/lemminx-maven/pull/34 so at least the default local and global settings should now be considered (eg mirrors available).

**Comment by gayanper** [comment] 2020-05-01 05:22
I will try building you branch and patching m2e.

**Comment by mickaelistria** [comment] 2020-05-01 17:19
Fixed with #34. Please close.

**Comment by gayanper** [comment] 2020-05-14 16:36
On windows with custom repository mirrors, the parent pom resolution doesn't work. "Non-resolvable parent POM for testing:workbench:0.0.1-SNAPSHOT: Could not find artifact"

**Comment by gayanper** [comment] 2020-05-14 16:55
I tried the same setting file at ~/.m2/settings.xml as well, but still the problem is there for parent artifact.

**Comment by gayanper** [comment] 2020-05-14 18:28
i even tried setting the m2e configuration using "/" instead of "\", doesn't help. It seems like the dependencies are also only resolved from default central repo.

**Comment by gayanper** [comment] 2020-05-14 19:02
I revert the #34 changes and tried with the `-Dmaven.conf` and it works without any problem.

**Comment by mickaelistria** [comment] 2020-05-14 19:42
Can you please elaborate how you did pass the maven.conf parameter? Did you have it running in m2e? What value did you pass?

**Comment by gayanper** [comment] 2020-05-15 15:23
I passed in the path to conf directory in my maven installation. The code before the fix #34 will read the setting.xml file from that location.
The mavem.conf was passed in as the System property with -D in eclipse.ini.

**Comment by gayanper** [comment] 2020-05-18 10:19
@mickaelistria @AObuchow event with the lastest lemminx-maven i still have the dependency resolution issues when we have a mirror repo in settings :(

**Comment by mickaelistria** [comment] 2020-05-18 10:22
Can you please try to write some unit test for LemMinX covering this issue?

**Comment by AObuchow** [comment] 2020-05-27 21:25
@gayanper this issue is still present, correct?

@mickaelistria maybe this should be added to the 0.0.1 milestone and prioritized for the release? Perhaps I can come up with a test or fix.

**Comment by mickaelistria** [comment] 2020-05-27 21:27
I apparently didn't merge the patch in m2e to force usage of more recent lemminx-maven, so the snapshot build uses Lemminx-Maven from the 15th (12 days ago) and misses numerous patches.
I'll try to merge the patch soon and will send a note here when m2e is available for further testing.

**Comment by AObuchow** [comment] 2020-05-27 21:29
@mickaelistria thanks for the update. Sounds good to me :)

**Comment by mickaelistria** [comment] 2020-05-27 23:07
@gayanper m2e was updated properly. Can you please try again?

**Comment by gayanper** [comment] 2020-05-28 07:44
@mickaelistria The problem is still there  with 1.16.0.20200527-2124. I still get error when resolving the parent pom `Non-resolvable parent POM for XXX: Could not find artifact XXX`

**Comment by mickaelistria** [comment] 2020-05-28 13:42
OK.
Can you please provide some exact steps to reproduce the issue? Ideally an example pom file, and some maven settings files and details about how those are set on filesystem and configured in m2e.

**Comment by mickaelistria** [comment] 2020-05-28 15:06
Can you please rework the project to a minimal reproducer that you can share? We really cannot make good progress without it.

**Comment by mickaelistria** [comment] 2020-06-04 07:32
@gayanper Can you help there regarding my previous comment? Without more specific example of how to reproduce very soon, this will miss 2020-06.

**Comment by gayanper** [comment] 2020-06-11 05:34
I tested this with latest build after windows file path fix. And it works now. Global settings are correctly taken into account.

**Comment by AObuchow** [comment] 2020-06-11 18:48
@gayanper awesome!! Thank you for reporting and testing this. I'm going to close this for now.

**Comment by gayanper** [comment] 2020-06-17 14:30
My mistake @AObuchow the global settings xml is not read. I had the global settings file sym linked to  ~/.m2/settings.xml on windows. If I remove this symbolic link I still get the error for parent pom resolutions.

**Comment by AObuchow** [comment] 2020-06-17 14:41
Thanks for reporting @gayanper, reopening.

**Comment by gayanper** [comment] 2020-06-17 15:48
A correction, I think the lemmix-maven needs to repository under ~/.m2/repository than the settings file.

**Comment by AObuchow** [comment] 2020-06-18 17:12
@gayanper I tried reproducing a simple test of setting a property in my global settings and checking for completion of that property. This feature doesn't seem to exist in the old m2e pom editor. 

If you're able to give some more specific details about how to reproduce, that'd help (are you setting a maven profile with a remote repository? or are you setting the <mirrors> in your settings.xml? Does m2e's old pom editor have the expected behavior?)

Part of my settings.xml:
```XML
 <profiles>
    <profile>
      <id>inject-application-home</id>
      <properties>
        <application-home>/path/to/application</application-home>
      </properties>
    </profile>

  </profiles>

  <activeProfiles>
    <activeProfile>inject-application-home</activeProfile>
  </activeProfiles>
```

I tried completing for `${application-ho}` in the legacy pom editor but didn't get any completion.

**Comment by AObuchow** [comment] 2020-06-18 19:11
Also, `<pluginGroups>` from the global settings.xml seems to work as expected.
I added `<pluginGroup>org.eclipse.tycho</pluginGroup>` and referenced the artifactId `<artifactId>tycho-compiler-plugin</artifactId>` without specifying a groupId and got no warning of unresolvable plugin, and hover works.

global settings.xml snippet:
```XML
  <pluginGroups>
    <pluginGroup>org.eclipse.tycho</pluginGroup>
  </pluginGroups>
```

Test pom.xml:
```XML
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
​
	<groupId>org.test</groupId>
	<artifactId>test</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	
	
<build>
	<plugins>
		<plugin>
			<artifactId>tycho-compiler-plugin</artifactId>
			<version>1.7.0</version>
		</plugin>
	</plugins>
</build>
```

Hover:
![image](https://user-images.githubusercontent.com/10300119/85062153-fb157980-b175-11ea-94b3-466ee2b28b78.png)

**Comment by AObuchow** [comment] 2020-06-25 04:06
Something that could be useful for CI/testing with GitHub Actions: https://github.com/marketplace/actions/maven-setings-action (although it seems to work only for non-global settings)

**Comment by AObuchow** [comment] 2020-06-26 17:54
I found something regarding maven profiles that might be useful/relevant in the Maven Model Builder source: https://github.com/apache/maven/blame/master/maven-model-builder/src/main/java/org/apache/maven/model/building/DefaultModelBuilder.java#L261

**Comment by AObuchow** [comment] 2020-06-26 19:13
Settings tests could potentially be written by setting a custom settings file, eg. [here](https://github.com/eclipse/lemminx-maven/blob/c568971c7e7837f46b71d4bf595a362305cf26c7/lemminx-maven/src/main/java/org/eclipse/lemminx/maven/MavenPlugin.java#L151).

Something to the effect of:
```Java
			File globalSettingsFile = overrideSettings ? getOverridenSettingsPath() : 
               getFileFromOptons(options.get("maven.globalSettings"), SettingsXmlConfigurationProcessor.DEFAULT_GLOBAL_SETTINGS_FILE);
			if (globalSettingsFile.canRead()) {
				mavenRequest.setGlobalSettingsFile(globalSettingsFile);
				Settings globalSettings = reader.read(globalSettingsFile, null);
				requestPopulator.populateFromSettings(mavenRequest, globalSettings);
			}
``

**Comment by mickaelistria** [comment] 2020-09-11 19:57
Closing as there is no feedback to my last question. Feel free to reopen and provide as much details to reproduce as possible if you can reproduce the issue with latest version.

**Closed by mickaelistria** 2020-09-11 19:57 UTC
Labels: bug
