### ISSUE TITLE
[feature] add code mining for executing plugin definitions in the pom

### ISSUE THREAD

**Issue by gayanper** [eclipse/lemminx-maven#284] opened 2022-03-08 15:43 UTC
Today in eclipse we don't have a way to execute plugins like inside the vscode which is provided by the java-maven plugin. One way to achieve this with what is offered by eclipse is to use code mining like in JUnit and Main method to trigger that plugin definition in a similar way how m2e execute predefined launchers. I'm open for more better suggestions to achieve the same.

WDYT ?

**Comment by mickaelistria** [comment] 2022-03-08 16:08
Duplicate of #6

**Closed by mickaelistria** 2022-03-08 16:08 UTC
