### ISSUE TITLE
A hidden NPE in MavenLemminxWorkspaceReader.findArtifact()

### ISSUE THREAD

**Issue by vrubezhny** [eclipse/lemminx-maven#274] opened 2022-02-24 13:43 UTC
A hidden NPE in MavenLemminxWorkspaceReader.findArtifact() prevents a project to be normally built.

```
java.lang.NullPointerException: Cannot invoke "org.apache.maven.artifact.Artifact.getGroupId()" because "artifact" is null
	at org.apache.maven.artifact.ArtifactUtils.key(ArtifactUtils.java:90)
	at org.eclipse.lemminx.extensions.maven.MavenLemminxWorkspaceReader.lambda$3(MavenLemminxWorkspaceReader.java:175)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findAny(ReferencePipeline.java:652)
	at org.eclipse.lemminx.extensions.maven.MavenLemminxWorkspaceReader.findArtifact(MavenLemminxWorkspaceReader.java:199)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:306)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:229)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:340)
	at org.apache.maven.project.DefaultProjectDependenciesResolver.resolve(DefaultProjectDependenciesResolver.java:191)
	at org.apache.maven.project.DefaultProjectBuilder.resolveDependencies(DefaultProjectBuilder.java:227)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:200)
	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:124)
	at org.eclipse.lemminx.extensions.maven.MavenProjectCache.getSnapshotProject(MavenProjectCache.java:116)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.computeFilesystemParent(MavenCompletionParticipant.java:393)
	at org.eclipse.lemminx.extensions.maven.participants.completion.MavenCompletionParticipant.onXMLContent(MavenCompletionParticipant.java:304)
	at org.eclipse.lemminx.services.XMLCompletions.collectInsideContent(XMLCompletions.java:768)
	at org.eclipse.lemminx.services.XMLCompletions.doComplete(XMLCompletions.java:247)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:151)
	at org.eclipse.lemminx.services.XMLLanguageService.doComplete(XMLLanguageService.java:146)
	at org.eclipse.lemminx.extensions.maven.participants.completion.CompletionParentTest.testParentArtifactCompletion(CompletionParentTest.java:68)
...
```

**Comment by mickaelistria** [comment] 2022-02-28 10:23
Duplicate of #274

**Closed by mickaelistria** 2022-02-28 10:23 UTC
